"""Add platform column to SentimentResult

Revision ID: 123610063731
Revises: 
Create Date: 2025-09-20 22:38:46.585971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123610063731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentiment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentiment_results', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
